# Site settings
# Used throughout the site for consistency.
title: ydata Portal | Business Intelligence for Netbox
lang: en-US
author: YDC GmbH
company_name: YDC GmbH
description: >-
  The ydata Portal is the intelligent business layer for your Netbox SoT. 
  Transform raw Netbox data into powerful DCIM tools for automated signal tracing,
  IT asset lifecycle management, and actionable datacenter operations reporting.
email: info@ydc.ch
contact_url: https://www.ydc.ch

# URL settings
# Centralized URLs for easy management, mirroring the source links.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.ydata.ch
main_website_url: https://www.ydata.ch
portal_login_url: https://portal.ydata.ch/login
devicesheet_tool_url: https://devicesheet.ydata.ch
documentation_url: /docs/

# SEO settings for jekyll-seo-tag
logo: /assets/img/appleicon.png
social:
  name: YDC GmbH
  links: [] # Add social media links here, e.g., https://twitter.com/jekyllrb

# Navigation
# Used to build the main navigation bar in the header.
navigation:
  - name: Features
    url: "#features"
  - name: Free Devicesheet Tool
    url: https://devicesheet.ydata.ch
    external: true
  - name: Documentation
    url: /docs/
  - name: Contact
    url: "#contact"

# Footer Links
# Used to build the links in the site footer.
footer_links:
  - name: Privacy Notice
    url: /privacy/
  - name: Documentation
    url: /docs/

# Build settings
markdown: kramdown

# SASS settings
# This 'load_paths' is the critical piece that tells Jekyll's SASS
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# This keeps your final site directory clean.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - shell.nix
  - .envrc
  - Justfile
  - package.json
  - package-lock.json
